OAUTH_CLIENT_ID: 946722529018-5b4p82rm8j3qf4h61nu73t8tsctjqvfq.apps.googleusercontent.com
OAUTH_CLIENT_SECRET: d47vgImdxghKB2hwRZFy2jEM
APPLICATION_CONFIG_SECRET_TOKEN: "<A LONG SECRET>"
GOOGLE_ANALYTICS: UA-54357304-2

staging:
  GOOGLE_ANALYTICS: UA-54357304-1
